/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade10.hierarquia.view;

/**
 *
 * @author Administrator
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        //f 2d
        chkCirc1.setVisible(false);
        chkQuad1.setVisible(false);
        chkTria1.setVisible(false);
        //f 3d
        chkEsfe1.setVisible(false);
        chkCubo1.setVisible(false);
        chkPira1.setVisible(false);
        //valor
        lblValor1.setVisible(false);
        txtEntradaValor1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProcessar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado1 = new javax.swing.JTextArea();
        chkEsfe1 = new javax.swing.JCheckBox();
        chkCubo1 = new javax.swing.JCheckBox();
        chkPira1 = new javax.swing.JCheckBox();
        chk2D1 = new javax.swing.JCheckBox();
        chk3D1 = new javax.swing.JCheckBox();
        txtEntradaValor1 = new javax.swing.JTextField();
        chkCirc1 = new javax.swing.JCheckBox();
        chkQuad1 = new javax.swing.JCheckBox();
        chkTria1 = new javax.swing.JCheckBox();
        lblValor1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProcessar1.setText("Processar Formas");
        btnProcessar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcessar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 35, -1, -1));

        txtResultado1.setEditable(false);
        txtResultado1.setColumns(20);
        txtResultado1.setRows(5);
        jScrollPane2.setViewportView(txtResultado1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 76, -1, -1));

        chkEsfe1.setText("Esfera");
        getContentPane().add(chkEsfe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 80, 20));

        chkCubo1.setText("Cubo");
        getContentPane().add(chkCubo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        chkPira1.setText("Piramide");
        getContentPane().add(chkPira1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 70, 30));

        chk2D1.setText("2D");
        chk2D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk2D1ActionPerformed(evt);
            }
        });
        getContentPane().add(chk2D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 36, -1, -1));

        chk3D1.setText("3D");
        chk3D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk3D1ActionPerformed(evt);
            }
        });
        getContentPane().add(chk3D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 36, -1, -1));
        getContentPane().add(txtEntradaValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 102, -1, -1));

        chkCirc1.setText("Circulo");
        getContentPane().add(chkCirc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 76, -1, -1));

        chkQuad1.setText("Quadrado");
        getContentPane().add(chkQuad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 103, -1, -1));

        chkTria1.setText("Triangulo");
        getContentPane().add(chkTria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 130, -1, -1));

        lblValor1.setText("Valor");
        getContentPane().add(lblValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 78, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcessar1ActionPerformed

    private void chk2D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk2D1ActionPerformed
        // TODO add your handling code here:
        if(chk2D1.isSelected() && !chk3D1.isSelected()){
            chkCirc1.setVisible(true);
            chkQuad1.setVisible(true);
            chkTria1.setVisible(true);
            lblValor1.setVisible(true);
            txtEntradaValor1.setVisible(true);
        }else{
            chkCirc1.setVisible(false);
            chkQuad1.setVisible(false);
            chkTria1.setVisible(false);
            lblValor1.setVisible(false);
            txtEntradaValor1.setVisible(false);
        }
    }//GEN-LAST:event_chk2D1ActionPerformed

    private void chk3D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk3D1ActionPerformed
        // TODO add your handling code here:
        if(chk3D1.isSelected() && !chk2D1.isSelected()){
            chkCirc1.setVisible(true);
            chkQuad1.setVisible(true);
            chkTria1.setVisible(true);
            lblValor1.setVisible(true);
            txtEntradaValor1.setVisible(true);
        }else{
            chkCirc1.setVisible(false);
            chkQuad1.setVisible(false);
            chkTria1.setVisible(false);
            lblValor1.setVisible(false);
            txtEntradaValor1.setVisible(false);
        }
    }//GEN-LAST:event_chk3D1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessar1;
    private javax.swing.JCheckBox chk2D1;
    private javax.swing.JCheckBox chk3D1;
    private javax.swing.JCheckBox chkCirc1;
    private javax.swing.JCheckBox chkCubo1;
    private javax.swing.JCheckBox chkEsfe1;
    private javax.swing.JCheckBox chkPira1;
    private javax.swing.JCheckBox chkQuad1;
    private javax.swing.JCheckBox chkTria1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JTextField txtEntradaValor1;
    private javax.swing.JTextArea txtResultado1;
    // End of variables declaration//GEN-END:variables
}
